print("i have 15 years old.. ")
print("i have 15 years old.. ")
print("i have 15 years old.. ")
print("i have 15 years old.. ")
print("i have 15 years old.. ")
print("ahmed")
print("ahmed")
print("ahmed")
print("ahmed")
print("ahmed")
